<a href="https://colab.research.google.com/github/irenechau31/Ass02_Craps/blob/master/Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy package for computing with arrays

In [3]:
import numpy as np

In [8]:
data=np.random.randn(2,3)
data

array([[-0.81253172, -1.2802145 ,  1.42926922],
       [ 0.32229988,  1.89094216,  0.57636539]])

In [9]:
data/2

array([[-0.40626586, -0.64010725,  0.71463461],
       [ 0.16114994,  0.94547108,  0.2881827 ]])

Ndarray stands for 'N-dimensional array'

Easy way to create an array is taking a sequance-like objects and passing it through the array function. NOTE: np.array as we imported numpy package as np

In [4]:
np.array([[1,2],[2,3],[5,6]], dtype=int)

array([[1, 2],
       [2, 3],
       [5, 6]])

In [5]:
np.array([[1,2],[2,3],[5,6]], dtype=float)

array([[1., 2.],
       [2., 3.],
       [5., 6.]])

Shape and Dimension data.shape or data.dimension, (2,3) => 2x3 array

the sahpe of every array is indicated by a tuple of each dimension

In [10]:
data.shape

(2, 3)

In [12]:
data.ndim #data dimension

2

a sequence-like object is automatically converted into a 1-dimensional array

In [13]:
data1=range(25)
arr1=np.array(data1)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Creating a 3-dimensional array

In [14]:
data3=[[[1,2], [1,2]],[[1,2],[1,2]]]
arr3=np.array(data3)
arr3

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [17]:
arr3.ndim

3

In [18]:
arr3.shape

(2, 2, 2)

Create an array with NaNs

Check dtype of given array using array_name.dtype

Convert data type, using ASTYPE

In [19]:
arr4=np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [20]:
arr4.dtype

dtype('float64')

In [21]:
arr4.astype(np.int32) #convert float to integer

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

Elementwise Computation

In [23]:
arr5=np.array([[1.,2.,3.],[4.,5.,6.]])
arr5

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
arr5**2 #power of 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [25]:
arr5/arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

Indexing and Slicing

In [36]:
arr6=np.arange(11)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr6[7]

7

In [38]:
arr6[-4:] #take four from the right

array([ 7,  8,  9, 10])

In [39]:
arr6[-4:]=0 #take four from the right, make it to 0

In [40]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0])

Indexing for higher dimension

In [42]:
arr2D=np.array([[1,2,3], [4,5,6],[7,8,9]])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr2D[2]

array([7, 8, 9])

In [44]:
arr2D[2][1]

8

In [61]:
import numpy as np
np.random.seed(10)
data=np.random.randn(2,4,3)
slice1=data[1,:,:].copy() #create a copy of the second matrix data[1,:,:]
#the negative element should be changed to 0
slice1[slice1<0]=0
#Positive element should be squared
slice1[slice1>0]=slice1[slice1>0]**2
#Add the resulting matric to the first  matrix data[0,:,:]
#=> Used .copy() to create a deep copy of the second matrix
#to ensure that the original data is not modified.
data[0,:,:]+=slice1 #update the first matrix with the results.
print(data)

[[[ 1.33158650e+00  1.77262655e+00 -1.49312856e+00]
  [ 1.89763644e-01  6.21335974e-01 -7.01823585e-01]
  [ 2.46936170e+00  1.08548526e-01  4.29143093e-03]
  [-1.74600211e-01  5.03819522e-01  6.89110654e+00]]

 [[-9.65065671e-01  1.02827408e+00  2.28630130e-01]
  [ 4.45137613e-01 -1.13660221e+00  1.35136878e-01]
  [ 1.48453700e+00 -1.07980489e+00 -1.97772828e+00]
  [-1.74337230e+00  2.66070164e-01  2.38496733e+00]]]
